apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ytdl-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: ytdl.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ytdl-webapp-service
                port:
                  number: 80
